package curc;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

@Path("asdf")
public class Library {
	
	@GET
	@Produces(MediaType.TEXT_PLAIN)
    public boolean someLibraryMethod() {
        return true;
    }
}
